#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH -N 1
#SBATCH -C cpu
#SBATCH -q debug
#SBATCH -J MINERvA-job_test
#SBATCH --mail-user=noeroy@yorku.ca
#SBATCH --mail-type=ALL
#SBATCH -A dune
#SBATCH -t 0:30:0

# OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

#run the application: 
srun -n 1 -c 256 --cpu_bind=cores run_minerva_nersc.sh 1
